on:
  push:
    paths-ignore:
    - README.md
    - LICENSE
jobs:
  test_wolfram:
    name: Test Wolfram language
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Run tests
      uses: miRoox/wolfram-action@master
      with:
        file: test/test.wls
      env:
        WOLFRAM_ID: ${{ secrets.WolframID }}
        WOLFRAM_PASS: ${{ secrets.WolframPW }}
