on:
  push:
    paths-ignore:
    - README.md
    - LICENSE
jobs:
  test_wolfram:
    name: Test Wolfram language
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Run tests
      uses: miRoox/wolfram-action@latest
      with:
        file: test/runtests.wls
      env:
        WOLFRAM_ID: ${{ secrets.WolframID }}
        WOLFRAM_PASS: ${{ secrets.WolframPW }}
  test_julia:
    name: Test Julia
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Set up Julia
      uses: julia-actions/setup-julia@latest
      with:
        version: 1.6
    - name: Run tests
      run: |
        julia --project=@. -e 'using Pkg
          Pkg.build()
          Pkg.test()'
  benchmark:
    name: Benchmark
    needs: [test_wolfram, test_julia]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Wolfram language Benchmark
      uses: miRoox/wolfram-action@latest
      with:
        file: benchmark/benchmark.wls
      env:
        WOLFRAM_ID: ${{ secrets.WolframID }}
        WOLFRAM_PASS: ${{ secrets.WolframPW }}
    - name: Set up Julia
      uses: julia-actions/setup-julia@latest
      with:
        version: 1.6
    - name: Julia Benchmark
      run: |
        julia --project=@. -e 'using Pkg
          Pkg.instantiate()
          evalfile("benchmark/benchmark.jl")'
